name: Tauri Multi-Platform Release

on:
  push:
    tags:
      - "v*"

jobs:
  tauri:
    strategy:
      matrix:
        platform: [ubuntu-22.04, windows-latest, macos-latest, macos-13]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: dtolnay/rust-toolchain@stable

      # Linux 依赖，仅在 Linux 下安装
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            patchelf \
            libglib2.0-dev

      - run: npm install
      - run: npm run build

      # Tauri 构建
      - run: npm run tauri build

      # 自动发布 Release，上传各平台所有主流产物
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            src-tauri/target/release/bundle/**/*.msi
            src-tauri/target/release/bundle/**/*.exe
            src-tauri/target/release/bundle/**/*.dmg
            src-tauri/target/release/bundle/**/*.app
            src-tauri/target/release/bundle/**/*.deb
            src-tauri/target/release/bundle/**/*.rpm
            src-tauri/target/release/bundle/**/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
